groups:
- name: heap_and_network_alerts
  rules:
  - alert: trop_de_load
    expr: node_load1 > 0.6
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "TEstYUp trop de load"
      description: "La charge du système (node_load1) a dépassé 0.6 pendant 1 minute."

  - alert: HighTcpConnections
    expr: node_netstat_Tcp_CurrEstab > 5
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Nombre élevé de connexions TCP établies"
      description: >
        Le nombre de connexions TCP établies a dépassé 100.
        Cela pourrait indiquer une surcharge ou une attaque potentielle (ex. DDoS).


