groups:
- name: heap_and_network_alerts
  rules:
  - alert: TropDeLoad
    expr: node_load1 > 0.8
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Trop de load"
      description: "La charge du système  a dépassé 0.8 pendant 1 minute."

  - alert: HighTcpConnections
    expr: node_netstat_Tcp_CurrEstab > 100
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Nombre élevé de connexions TCP établies"
      description: >
        Le nombre de connexions TCP établies a dépassé 10.
        Cela pourrait indiquer une surcharge ou une attaque potentielle (ex. DDoS).

  - alert: HighMemoryUsage
    expr: 100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Utilisation mémoire élevée"
      description: >
        La mémoire utilisée dépasse 80 %.


  - alert: HighNetworkReceiveErrors
    expr: rate(node_network_receive_errs_total[1m]) > 10
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Nombre élevé d'erreurs de réception réseau détectées."


  - alert: HighDiskUsage
    expr: 100 * (node_filesystem_size_bytes{fstype!~"tmpfs|fuse.*"} - node_filesystem_free_bytes{fstype!~"tmpfs|fuse.*"}) / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.*"} > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Utilisation élevée du disque."
      description: "Utilisation dépasse 80 %."

