groups:
- name: heap_alerts
  rules:
  - alert: HighHeapAllocation
    expr: go_gc_heap_allocs_bytes_total > 270000000
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "TEstYUp Allocation mémoire GC élevée"
      description: "La métrique go_gc_heap_allocs_bytes_total a dépassé 270000000."
