global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_services'
    static_configs:
      - targets:
          - "192.168.10.5:3000"  # Grafana
          - "192.168.10.6:9093"  # AlertManager

  - job_name: 'machines'
    static_configs:
      - targets:
          - "10.0.2.15:9100"

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "192.168.10.6:9093"
