global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_services'
    static_configs:
      - targets:
          - "{{ hostvars['grafana']['ansible_default_ipv4']['address'] }}:3000"  # Grafana
          - "{{ hostvars['alertmanager']['ansible_default_ipv4']['address'] }}:9093"  # AlertManager

  - job_name: 'machines'
    static_configs:
      - targets:
          - "{{ hostvars['hote']['ansible_default_ipv4']['address'] }}:9100"

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "{{ hostvars['alertmanager']['ansible_default_ipv4']['address'] }}:9093"
