global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_services'
    static_configs:
      - targets:
          - "{{ groups['grafana'][0] }}:3000"  # Grafana
          - "{{ groups['alertmanager'][0] }}:9093"  # AlertManager

  - job_name: 'machines'
    static_configs:
      - targets:
          - "{{ groups['hote'][0] }}:9100"

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "{{ groups['alertmanager'][0] }}:9093"
