---
- name: Déployer la configuration et les règles d'alerte pour Prometheus
  hosts: localhost
  tasks:
    - name: S'assurer que le conteneur Prometheus est démarré
      docker_container:
        name: prometheus
        state: started

    - name: Copier prometheus.yml dans le conteneur Prometheus
      command: docker cp "../roles/prometheus/files/prometheus.yml" prometheus:/etc/prometheus/prometheus.yml

    - name: Copier alert_rules.yml dans le conteneur Prometheus
      command: docker cp "../roles/prometheus/files/alert_rules.yml" prometheus:/etc/prometheus/alert_rules.yml

    - name: Arrêter le conteneur Prometheus
      docker_container:
        name: prometheus
        state: stopped

    - name: Démarrer le conteneur Prometheus
      docker_container:
        name: prometheus
        state: started

    - name: Copier alertmanager.yml dans le conteneur Alertmanager
      command: docker cp "../roles/alertmanager/files/alertmanager.yml" alertmanager:/etc/alertmanager/alertmanager.yml

    - name: Arreter le conteneur Alertmanager
      docker_container:
        name: alertmanager
        state: stopped

    - name: Démarrer le conteneur Alertmanager
      docker_container:
        name: alertmanager
        state: started
