---
- name: Créer un réseau Docker
  hosts: localhost
  become: true
  tasks:
    - name: Vérifier que le moteur Docker est en cours d'exécution
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Créer un réseau Docker
      community.docker.docker_network:
        name: projetsae
        driver: bridge
        ipam_config:
          - subnet: 192.168.10.0/24
        state: present
