---
- name: Configuration de Grafana
  hosts: localhost
  tasks:
    - name: Ajouter la source de données Prometheus
      uri:
        url: "http://192.168.10.5:3000/api/datasources"
        method: POST
        user: "admin"
        password: "quentin"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "url": "http://192.168.10.4:9090",
            "access": "proxy",
            "isDefault": true
          }
        body_format: json
        status_code: 200
        validate_certs: false
